require('base')
require('maps')
require('plugins')
require('styles')
require('colors')
require('text')

require('impatient')

require('p-lsp')
require('p-lualine')
require('p-telescope')
require('p-lspkind')
require('p-cmp')
require('p-bookmark')
require('p-treesitter')
require('p-tree')
require('p-indent')
require('p-indentscope')
require('p-undotree')
require('p-neogit')
require('p-compile')
require('p-harpoon')
require('p-dap')
