require('base')
require('maps')
require('plugins')
require('styles')
require('colors')
require('text')

require('p-lsp')
require('p-lualine')
require('p-telescope')
require('p-lspkind')
require('p-cmp')
require('p-bookmark')
require('p-treesitter')
require('p-mason')
require('p-tree')
